# Generated by Django 4.0.1 on 2022-03-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='budget',
            field=models.PositiveIntegerField(help_text='en DRH'),
        ),
    ]
